### ISSUE TITLE
Docs: How to pass empty string value to yaml-set and yaml-merge

### ISSUE THREAD

**Issue by AndydeCleyre** [wwkimball/yamlpath#71] opened 2020-10-07 21:06 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I need to set a value that *may be* an empty string.

**Describe the solution you'd like**
A note in the `yaml-set` and `yaml-merge` docs about properly passing the empty string as a value.

**Describe alternatives you've considered**

```console
$ printf '%s\n' 'oldkey: "4"' >vars.yml
$ yaml-set -g .newkey -a '' vars.yml
ERROR:  Exactly one of the following must be set:  --value, --file, --stdin, or --random
Please try --help for more information.
$ yaml-merge -m .newkey vars.json - <<<''
$ # retcode 3
$ yaml-merge -m . vars.json - <<<'newkey: '
--- {"oldkey": "4", "newkey": !!null ''}
```

**Comment by wwkimball** [comment] 2020-10-07 21:56
In this case, you've found a known issue with the present version of `yaml-merge`, which is already in the updated CHANGES file, `Bug Fixes:` section, for the next version:

```text
* When the left-most document was JSON, yaml-merge would improperly write out
  a YAML document start mark (---) and then a hybrid JSON/YAML result rather
  than valid JSON.
```

I've already fixed this issue for the next release.

As for `yaml-set` not accepting an empty-string as a value, that is just a case of an unexpected use-case.  You're on a roll today with those.  😃 

I simply never considered that anyone would deliberately want to set an empty-string; to wit, I consider an opposite case where such an attempt is accidental due to some error in a variable or its spelling like:

```shell
myVariable="Some value for my YAML/JSON/Compatible file"
yaml-set --change=/some/path --value="$myMisspelledVariable" myfile.yaml
```

**Open for discussion**:
Should `yaml-set` continue to protect against what could very easily be an accidental erasure of data, or just allow empty values?

Notwithstanding the JSON output bug, you can accomplish your goal with `yaml-merge` if you provide some missing structure.  You did above, in fact, send a NULL value for `yaml-merge` to chew on and it correctly set the value accordingly.  In this specific case, when supplying (Pythonic or real) JSON from the command-line for merge, be sure to add just enough structure to indicate you are merging a Hash that has a key with an empty-string value.  Remember that you aren't sending in "raw text resembling some literal YAML/JSON" to be "injected verbatim into the file".  Rather, you are meant to merge "valid YAML/JSON" into another valid document.  For example, this accomplishes your goal:

```shell
$ yaml-merge --mergeat=/ vars.yml <<<'{newkey: ""}'
---
newkey: ""
```

To demonstrate that the next version of `yaml-merge` properly handles JSON:

```shell
$ echo "{oldkey: 4}" >vars.json

$ cat vars.json
{oldkey: 4}

$ yaml-merge vars.json <<<"{newkey: ''}"
{"oldkey": 4, "newkey": ""}
```

I can update `yaml-set` to permit setting empty values if you strongly believe that is better than protecting against data erasure.

**Comment by AndydeCleyre** [comment] 2020-10-09 19:20
Thanks for the explanation!

Here's a sample use case that I'm wondering about:

```zsh
#!/bin/zsh -fe

format="${1:-rst}"
case $format in
  rst)    string='.. content::\n   :depth: 1' ;;
  mdbook) string='<!-- toc -->'               ;;
  sphinx) string=''                           ;;
  *)      return 1                            ;;
esac

if [[ $string ]]; then
  yaml-merge -m .toc vars.json - <<<"$string"
  # >vars.json
else
  yaml-merge -m . vars.json - <<<'{"toc": ""}'
  # >vars.json
fi
```
The idea is to insert into `vars.json` at key `toc` the appropriate syntax for a table of contents, which we will omit from a template render process by using the empty string.

Notes on the above snippet:

- Those commented redirections aren't right; they maybe overwrite the input file too early, resulting in

```
CRITICAL:  The first input file, vars.json, has nothing to merge into.
# retcode 1
```
and an empty `vars.json`. I guess I need to write to a tempfile, then copy into place.
- I use a different block to handle the empty string case, because I don't want to worry about the value of `string` needing special escape handling to play nice with the json string. This touches on your point about *merging yaml docs* rather than *inserting values* -- `yaml-set` may be a better fit for this one. In fact, I guess I'm in trouble here if `string` happens to be valid yaml. I want to be able to set a string value at a certain location without worrying about escaping and types.
- I could instead rely on `null` or `false`, and extra logic, but it is my general pattern to treat each yaml scalar as string until made otherwise by an in-code schema or function, along the lines of [strictyaml](https://hitchdev.com/strictyaml/) (where the yaml itself only has `str`, `list`, and `dict`, and other types are the apps' concern. I know that's a departure from the official spec, but FWIW for perspective:

```python
In [1]: from strictyaml import load

In [2]: yamlstr='''
   ...: realempty:
   ...: emptystr: ''
   ...: isitnull: null
   ...: '''

In [3]: yaml = load(yamlstr)

In [4]: dict(yaml.data)
Out[4]: {'realempty': '', 'emptystr': '', 'isitnull': 'null'}

In [5]: from strictyaml import MapPattern, Str, EmptyNone

In [6]: yaml = load(yamlstr, MapPattern(Str(), EmptyNone() | Str()))

In [7]: dict(yaml.data)
Out[7]: {'realempty': None, 'emptystr': None, 'isitnull': 'null'}
```

Thanks for your continued work on this great project!

**Comment by wwkimball** [comment] 2020-10-09 19:55
You have presented a valid use-case for permitting empty values to be deliberately set in YAML/JSON/Compatible files via yaml-set.  I'm adding this enhancement to the CHANGES log for the upcoming release and will update yaml-set accordingly (yaml-merge already allows it with sufficient structure in the input).

You also presented a use-case that has been simmering in the back of my thoughts for a while:  allow yaml-merge to replace one of its input files. This is tricky but not impossible.  I originally did not permit this for two reasons:

1. The file is open while the code is reading through it.  As you've found, it is hazardous to change files while reading them.
1. I'm very protective of data; I prefer idempotent operations (repeatable with predictable outcome and without undue consequence).  The idea of altering a file by an operation that is reading and -- by design -- modifying the content, goes against that principle.

However, my second reason was greatly weakened the moment I enabled access to STDIN, which has no file to overwrite.  Your use-case demonstrates a very good reason to permit overwriting files and in my own hand-tests, I often want to overwrite existing files, as well.  However, I still prefer caution, so I will enable overwrites, but not by default.  Since a flag like `--force` is often misused or misunderstood, I'll add a mutually-exclusive option alongside `--output` named `--overwrite`.  Therefore, users must consciously indicate they are willingly destroying one of the command's source files, replacing its content with the merge result.  Keeping in line with my cautious principle, I'll also add a new `--backup` flag that will behave identically to that of yaml-set when `--overwrite` is used.

On a related note, you're about to stumble into another but I've already fixed for the next release:  The yaml-set command, when operating against pure JSON files, improperly writes out the YAML Start-of-Document marker to the updated JSON file on the same line as the JSON content, creating output like:

```json
--- {"the": "document"}
```

This was accidental and has been corrected for the next release.

**Comment by wwkimball** [comment] 2020-10-10 20:55
The original issue and add-on enhancements reported/requested in this issue have all been addressed in the pending release.  I'm shaking out the new code by updating documentation to the Wiki.  I sometimes find issues or "It'd be nice if I could do ____________ to solve this use-case." while doing so.  I am planning to release the next version by mid next week.

**Closed** 2020-10-13 19:50 UTC
Labels: bug, documentation

**Comment by AndydeCleyre** [comment] 2020-10-23 17:48
Excellent, thanks!
